spring.profiles.active: development
spring:
  http:
    multipart:
      file-size-threshold: 10MB
      max-file-size: 10MB
      max-request-size: 10MB
---
spring:
  profiles: cloud
  application:
    name: ${vcap.application.name:s3-sample-app}
amazon:
  aws:
    access-key-id: ${vcap.services.s3-service.credentials.accessKeyId:access-key-id}
    access-key-secret: ${vcap.services.s3-service.credentials.secretAccessKey:access-key-secret}
  s3:
    default-bucket: ${vcap.services.s3-service.credentials.userName:default-bucket}
---
spring:
  profiles: development
  application:
    name: s3-sample-app
amazon:
  aws:
    access-key-id: replace
    access-key-secret: replace
  s3:
    default-bucket: replace
